Parse assists from match data - Fix ellipses for long names in match datapoints
pubgsh/client pull request #67
Opened 2020-11-03 23:08 UTC by bmarley

![Screen Shot 2020-11-03 at 3 55 13 PM](https://user-images.githubusercontent.com/2301918/98050389-d3564380-1dee-11eb-9c60-5cfb0d906ae0.png)

2020-11-03 23:15 UTC, apazzolini requested changes

2020-11-03 23:15 UTC, apazzolini commented on src/components/MatchPlayer/Roster/index.js
> +    grid-template-columns: 75px .25fr .25fr .5fr;
iirc the intent of hard-coding the width for kills and damage and letting the player's name take up the remaining free space was to align the kills/damage for all people in the match.

Can you confirm this doesn't cause misalignment?

2020-11-04 00:06 UTC, bmarley commented on src/components/MatchPlayer/Roster/index.js
> +    grid-template-columns: 75px .25fr .25fr .5fr;
Leaving the name as a flexrow breaks the alignment/css (current state - see ss (lmao don't mind the name)
![Screen Shot 2020-11-03 at 5 03 47 PM](https://user-images.githubusercontent.com/2301918/98053865-d3f2d800-1df6-11eb-97f8-503b1b0de297.png)
) - confirmed alignment with changes - see ss
![Screen Shot 2020-11-03 at 5 03 47 PM](https://user-images.githubusercontent.com/2301918/98053769-955d1d80-1df6-11eb-872c-61373cf99170.png)

2020-11-04 00:09 UTC, merged

2020-11-04 00:10 UTC, apazzolini commented
Congrats on your first ever PR!