Add support for Assists with event LogPlayerKillV2
pubgsh/client pull request #81
Opened 2021-07-09 18:39 UTC by lovethebomb

Hey, with #80, I noticed also that the Telemetry event switched from the convenient `assistant` to `assists_AccountId`.

This PR attempts to fix Assists parsing in a crude way, during my tests initial parsing performance wasn't too impacted, but perhaps there is a better to do that?

2021-07-09 19:09 UTC, apazzolini requested changes
Great catch on the updated format. I was admittedly lazy and just updated the key 😅. I think your solution is reasonable performance-wise, will merge after the small nit!

2021-07-09 19:09 UTC, apazzolini commented on src/models/Telemetry.parser.js
> +                        return players.map(p => incrementPlayerStateVal(p.name, 'assists', 1))
Nit: Can we convert both of these `map` calls to `forEach`? They're side-effectual and we're not using the resulting array, so I think it's a little more appropriate.

2021-07-09 20:34 UTC, lovethebomb commented on src/models/Telemetry.parser.js
> +                        return players.map(p => incrementPlayerStateVal(p.name, 'assists', 1))
I've updated the code, can you check if it matches your suggestions?

2021-07-09 20:50 UTC, apazzolini approved these changes

2021-07-09 20:50 UTC, merged

2025-02-03 10:59 UTC, Salem10seko approved these changes